package com.vaadin.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.NativeSelect;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.VerticalSplitPanel;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ReportsOverviewDesign extends VerticalLayout {
	protected VerticalSplitPanel splitPanel;
	protected ComboBox projectsComboBox;
	protected Button userButton;
	protected Button logoutButton;
	protected Button reportBugButton;
	protected Button requestFeatureButton;
	protected Button manageProjectButton;
	protected TextField searchTextField;
	protected NativeSelect versionsComboBox;
	protected HorizontalLayout optionsLayout;
	protected Button buttonAssigneesOnlyMe;
	protected Button buttonAssigneesEveryone;
	protected Button buttonStatusOpen;
	protected Button buttonStatusAll;
	protected Button buttonStatusCustom;
	protected Table artifactTable;

	public ReportsOverviewDesign() {
		Design.read(this);
	}
}
