package com.vaadin.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.NativeSelect;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.VerticalSplitPanel;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ReportDetailsDesign extends VerticalLayout {
	protected VerticalLayout controlsContainer;
	protected Button openInWindowButton;
	protected Label artefactSummary;
	protected Label artefactSummaryExtension;
	protected NativeSelect priorityComboBox;
	protected NativeSelect typeComboBox;
	protected NativeSelect statusComboBox;
	protected NativeSelect assignedToComboBox;
	protected NativeSelect versionComboBox;
	protected Button updateButton;
	protected Button revertButton;
	protected VerticalSplitPanel detailsSplitPanel;
	protected TextArea detailsTextArea;
	protected VerticalLayout commentSection;
	protected TextArea commentTextArea;
	protected HorizontalLayout attachmentsBar;
	protected Button doneButton;
	protected Button attachmentButton;
	protected Button cancelButton;

	public ReportDetailsDesign() {
		Design.read(this);
	}
}
